title: PycrucibleClient Documentation
description: Python client library for the Crucible API
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

markdown: kramdown
highlighter: rouge

github:
  repository_url: https://github.com/your-username/pycrucible

navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: Tutorial
    url: /tutorial
  - title: API Reference
    url: /api-reference
  - title: Examples
    url: /examples